apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    resourceType: core
    resourceName: core
  name: sift-etl
spec:
  serviceName: sift-etl-service
  replicas: 1
  selector:
    matchLabels:
      app: sift-etl-pod
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::641793388528:role/OpoloResilienceEC2InstanceRole
      labels:
        app: sift-etl-pod
        resourceType: core
        resourceName: core
    spec:
      containers:
      - name: sift-etl
        image: sandeeps96/sift-core:V4.5.0-sift-etl-TelstraResilience
        imagePullPolicy: Always
        env:
        - name: DS_NAME
          value: sift-etl
        - name: PERSIST_ADDRESS
          value: 10.193.33.106,10.193.33.238,10.193.34.15,10.193.35.50
        - name: LOG_LEVEL
          value: info
        - name: HEAP_SIZE
          value: 1500m
        - name: JVM_PARAM
          value: -XX:+UseConcMarkSweepGC
        - name: ELASTICSEARCH_URL
          value: http://elk-aws.uat.th.intranet:9200 
        - name: ELASTICSEARCH_SIFT_LOGS_INDEX
          value: siftEtllogs
        - name: CONTAINER_ID
          value: siftETL
        - name: ELASTICSEARCH_SIFT_FILREPORT_INDEX
          value: pandastats
        - name: ELASTICSEARCH_SIFT_BADRECORDS_INDEX
          value: siftbadrecords
        - name: PERSIST_CLIENT
          value: couchbasev7
        - name: SLEEPTIME
          value: '1'
        - name: PERSIST_SSL
          value:  /opt/couchbase/ssl/opolo_couchbase_cluster_np.pem
        - name: PERSIST_USERNAME
          value: opolonp
        - name: PERSIST_PASSWORD
          value: 0polodef23
        - name: CONFIG_BUCKET
          value: opolo_config_np
        - name: DEFAULT_BUCKET
          value: opolo_default_np
        - name: APP_LOG_LEVEL
          value: INFO
        - name: LOG_TYPE
          value: file
        - name: NAMESPACE
          value: opolo
        - name: SIFT_ETL_PATH
          value: /opt/knowesis/sift/core/sift/scripts/ETLExtract/input/
        - name: SPLITTER_KEY
          value: MSISDN
        resources:
          limits:
            cpu: '2'
            memory: 2G
          requests:
            cpu: 100m
            memory: 1G
        volumeMounts:
        - name: persistent-storage
          mountPath: /data
        - mountPath: /opt/knowesis/sift/core/sift/scripts/ETLExtract/
          name: etl-input-data
        - mountPath: /opt/couchbase/ssl/opolo_couchbase_cluster_np.pem
          subPath: opolo_couchbase_cluster_np.pem
          name: couchbase-pem-volume
      imagePullSecrets:
      - name: sift-cred
      nodeSelector:
        deployETL: 'true'
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: efs-claim
      - name: etl-input-data
        hostPath:
         path: /opt/knowesis/sift/data/core/sift/scripts/ETLExtract/
      - name: couchbase-pem-volume
        configMap:
          name: couchbase-pem
