apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-pod
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::641793388528:role/OpoloResilienceEC2InstanceRole
      labels:
        app: docker-pod
    spec:
      imagePullSecrets:
      - name: sift-cred
#      nodeSelector:
#        deploySoOpolo: "true"
      containers:
      - name: docker
        image: docker
        resources:
          requests:
            cpu: 100m
            memory: 100M
          limits:
            #cpu: 1
            #memory: 500M
        imagePullPolicy: Always
