apiVersion: v1
kind: Service
metadata:
  name: siftportal
  labels:
    app: portal-master-pod
spec:
  ports:
    - port: 8080
      name: web
  selector:
    app: portal-master-pod
  type: ClusterIP
