apiVersion: v1
kind: Service
metadata:
  name: couchbase-ui
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: true
    external-dns.alpha.kubernetes.io/hostname: couchbase-ui.sdpamp.internal
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8091
    targetPort: 8091
  selector:
    k8s-app: sift-persist-pod
  type: LoadBalance
