apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-persist-volume
spec:
  capacity:
    storage: 60Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  awsElasticBlockStore:
    volumeID: vol-05a8c563bf7b81152
    fsType: ext4
