apiVersion: v1
kind: Service
metadata:
  name: opolo-admin
  labels:
    app: opolo-admin-pod
spec:
  ports:
    - port: 3000
  selector:
    app: opolo-admin-pod
#  type: ClusterIP
  type: NodePort
    #clusterIP: None