apiVersion: v1
kind: Service
metadata:
  name: opolo-entry-event
  labels:
    app: opolo-entry-event-pod
spec:
  ports:
    - name: http0
      port: 3006
  selector:
    app: opolo-entry-event-pod
  type: ClusterIP
