apiVersion: v1
kind: Service
metadata:
  name: opolo-policy
  labels:
    app: opolo-policy-pod
spec:
  ports:
    - name: http0
      port: 3004
  selector:
    app: opolo-policy-pod
  type: ClusterIP
