apiVersion: apps/v1
kind: Deployment
metadata:
  name: opolo-real
  labels:
    resourceName: opolo-real
    resourceType: opolo
spec:
  #serviceName: "opolo-real"
  replicas: 1
  selector:
    matchLabels:
      app: opolo-real-pod
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::641793388528:role/OpoloResilienceEC2InstanceRole
      labels:
        app: opolo-real-pod
        resourceName: real
        resourceType: opolo
    spec:
      nodeSelector:
        deployOpoloReal: "true"
      imagePullSecrets:
      - name: sift-cred
      containers:
      - name: opolo-real
        image: knowesis/opolo-real:V2.0.0-TELSTRA-DEV
        resources:
          requests:
            cpu: 200m
            memory: 3072Mi
          limits:
            cpu: 200m
            memory: 3072Mi
        imagePullPolicy: Always
        ports:
        - containerPort: 3013
        envFrom:
          - configMapRef:
              name: opolo-real-cm
