apiVersion: apps/v1
kind: Deployment
metadata:
  name: opolo-patternmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opolo-patternmanager-pod
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::641793388528:role/OpoloResilienceEC2InstanceRole
      labels:
        app: opolo-patternmanager-pod
        ResourceGroup: so
    spec:
      imagePullSecrets:
        - name: sift-cred
      nodeSelector:
        deploySoOpolo: "true"
      containers:
        - name: opolo-patternmanager
          image: knowesis/sift-so:so-patternmanager-4.0-TELSTRA
          resources:
            requests:
                cpu: 100m
                memory: 100M
            limits:
                cpu: 1
                memory: 500M
          imagePullPolicy: Always          
          envFrom:
          - configMapRef:
              name: so-opolo-patternmanager-cm
