apiVersion: apps/v1
kind: Deployment
metadata:
  name: opolo-smshandler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opolo-smshandler-pod
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::641793388528:role/OpoloResilienceEC2InstanceRole
      labels:
        app: opolo-smshandler-pod
        ResourceGroup: so
    spec:
      imagePullSecrets:
         - name: sift-cred
      nodeSelector:
        deploySoOpolo: "true"
      containers:
      - name: opolo-smshandler
        image: knowesis/sift-so:so-smshandler-opolo.4.0-TELSTRA
        resources:
          requests:
            cpu: 100m
            memory: 100M
          limits:
            cpu: 1
            memory: 500M
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: so-opolo-smshandler-cm
