apiVersion: v1
kind: Service
metadata:
  name: siftapi
  labels:
    app: siftapi-master-pod
spec:
  ports:
    - port: 10080
      name: ptapi
  selector:
    app: siftapi-master-pod
  type: ClusterIP