apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: opolo-sift-aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "arn:aws:secretsmanager:ap-southeast-2:641793388528:secret:opolo/sift/test-i5b4qz"
          objectType: "secretsmanager"
