apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: opolo
  name: siftmanage
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["*"]
  verbs: ["create" , "delete" , "get", "watch", "list"]
- apiGroups: ["apps"] # "" indicates the core API group
  resources: ["*"]
  verbs: ["create" , "delete" , "get", "watch", "list"]
