apiVersion: apps/v1
kind: Deployment
metadata:
  name: opolo-mpscloudhandler
spec:
  selector:
    matchLabels:
      app: opolo-mpscloudhandler-pod
  replicas: 1
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::641793388528:role/OpoloResilienceEC2InstanceRole
      labels:
        app: opolo-mpscloudhandler-pod
        ResourceGroup: so
    spec:
      imagePullSecrets:
      - name: sift-cred
      nodeSelector:
        deploySoOpolo: "true"
      containers:
      - name: opolo-mpscloudhandler
        image: knowesis/sift-so:so-mps-cloud-handler-4.0-TELSTRA
        resources:
          requests:
            cpu: 100m
            memory: 100M
          limits:
            cpu: 1
            memory: 500M
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: so-opolo-mpscloudhandler-cm
        volumeMounts:
        - mountPath: /opt/knowesis/sift/certs/okapi-client.jks
          subPath: okapi-client.jks
          name: client-volume
        - mountPath: /opt/knowesis/sift/certs/okapi-server.jks
          subPath: okapi-server.jks
          name: server-volume
      volumes:
      - name: client-volume
        configMap:
          name: client-jks
      - name: server-volume
        configMap:
          name: server-jks
