apiVersion: v1
kind: Service
metadata:
  name: sfmcapi
  labels:
    app: sfmcapi-master-pod
spec:
  ports:
    - port: 8090
      name: sfapi
  selector:
    app: sfmcapi-master-pod
  type: ClusterIP